### ISSUE TITLE
Rebase commits not included in 1.6.0 tarball

### ISSUE THREAD

**Issue by cottsay** [ros-gbp/pcl-release#1]
It looks like the rebase commits are not included in the current 1.6.0 tarball. This causes source installs to fail on Groovy for (at least) Fedora. Pulling from the master branch compiles correctly. Would this require a version bump or could the tarball just be updated?

**Comment by tfoote** [comment]
What tarball are you pulling?

**Comment by cottsay** [comment]
https://github.com/ros-gbp/pcl-release/archive/release/pcl/1.6.0.tar.gz does not build, but pulling pcl-release master does.
